title: Mac Goodwin
description: >- # this means to ignore newlines until "baseurl:"
  My Portfolio of Programming and Writing Projects
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mac__goodwin
github_username:  Twigonometry

blog_categories:
- WILT
- WILF
- HTB
- Cyber

collections:
  prog-showcases:
    output: true
  writing-showcases:
    output: true
  
sass:
  sass_dir: ./_sass